# Generated by Django 3.2.16 on 2022-12-29 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221229_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=500, null=True)),
                ('message', models.TextField(max_length=1000, null=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
