# Generated by Django 3.2.16 on 2022-12-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_message_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
