# Generated by Django 3.2.16 on 2022-12-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
