# Generated by Django 3.2.16 on 2023-01-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_review_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_on']},
        ),
    ]
