# Generated by Django 3.2.16 on 2023-01-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_on']},
        ),
    ]
