# Generated by Django 3.2.16 on 2023-01-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sculptures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sculpture',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sculpture',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
