# Generated by Django 3.2.16 on 2023-01-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sculptures', '0002_auto_20230102_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sculpture',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default='Add Quantity Here...', max_digits=3),
        ),
    ]
