# Generated by Django 3.2.16 on 2023-01-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sculptures', '0003_alter_sculpture_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sculpture',
            name='detailed_description',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
