# Generated by Django 3.2.16 on 2023-01-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sculptures', '0004_sculpture_detailed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sculpture',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
