# Generated by Django 3.2.16 on 2023-01-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sculptures', '0005_alter_sculpture_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sculpture',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='detailed_description',
            field=models.TextField(max_length=500),
        ),
    ]
