# Generated by Django 3.2.16 on 2023-07-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sculptures', '0006_auto_20230117_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sculpture',
            options={'ordering': ['-available']},
        ),
    ]
